Feature/stats monitor microservice
GodlyCat/Pokemons pull request #22
Opened 2023-05-02 09:02 UTC by SasukeVapes

Added Microservice with Regular DAL and DALExternal

2023-05-02 09:45 UTC, blackberts approved these changes

2023-05-02 09:53 UTC, Glipchik commented on StatsMonitor/StatsMonitor.DAL/DI/DependencyInjection.cs
> +        public static void AddDependenciesDalLayer(this IServiceCollection services, IConfiguration config)
Either DALLayer or DAL, not DalLayer

2023-05-02 09:54 UTC, Glipchik approved these changes

2023-05-02 14:49 UTC, GodlyCat requested changes

2023-05-02 14:49 UTC, GodlyCat commented on StatsMonitor/StatsMonitor.BLL/Jobs/UpdateMultipleStatsJob.cs
> +                if (pOw.Hunger < 0.5m && pOw.Hunger > 0)
move 0, 0.5m , 0.25m to constants

2023-05-02 14:49 UTC, GodlyCat commented on StatsMonitor/StatsMonitor.BLL/Jobs/UpdateStatsJob.cs
> +            var pokemonOwners = await _pokemonOwnerExternalService.GetPokemonOwners(token);
Why you have 2 similar jobs ?

2023-05-02 14:49 UTC, GodlyCat commented on StatsMonitor/StatsMonitor.BLL/Jobs/UpdateStatsJob.cs
> +        public async Task Execute(IJobExecutionContext context)
Move this part to service and invoke method from service in job

2023-05-02 14:49 UTC, GodlyCat commented on StatsMonitor/StatsMonitor.BLL/Services/PokemonService.cs
> +    public class PokemonService : IPokemonService
Are you sure about count of methods ? (currently needed only one)

2023-05-02 14:49 UTC, GodlyCat commented on StatsMonitor/StatsMonitor.BLL/Services/PokemonOwnerService.cs
> +        public async Task<PokemonOwner> UpdatePokemonOwner(int ownerId, int pokemonId, PokemonOwner updatedPokemonOwner, CancellationToken cancellationToken)
Why update use both ids instead of PoW id ?

2023-05-08 13:48 UTC, GodlyCat approved these changes

2023-05-08 14:02 UTC, merged