Added Controllers,CRUD,MappingProfiles,ShortVM
GodlyCat/Pokemons pull request #4
Opened 2023-02-08 12:14 UTC by SasukeVapes

2023-02-08 12:41 UTC, Genresal commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +        }
Add a blank line after the if statement there and in other places, please.

2023-02-08 12:41 UTC, Genresal commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +
There is possible use of a single FirstOrDefault call.

2023-02-08 12:41 UTC, Genresal commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +            return Ok("Successfully created");
Remove the extra blank line, please.

2023-02-08 12:41 UTC, Genresal commented on PokemonReviewApi/PokemonReviewApi/Controllers/CountryController.cs
> +
The same point about FirstAndDefault.

2023-02-08 13:43 UTC, Genresal approved these changes

2023-02-09 12:53 UTC, GodlyCat requested changes

2023-02-09 12:53 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CountryController.cs
> +            if (!ModelState.IsValid)
Better to remove ModelState.IsValid

2023-02-09 12:53 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Helper/MappingProfiles.cs
> +            CreateMap<CategoryViewModel, CategoryEntity>();
This unnecessary at all, because we have short view models

2023-02-09 12:53 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/OwnerController.cs
> +        public IActionResult UpdateOwner(int ownerId, [FromBody] OwnerViewModel updatedOwner)
same

2023-02-09 12:53 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +            var categoryMap = _mapper.Map<CategoryEntity>(updatedCategory);
add id to model after mapping

2023-02-16 11:00 UTC, GodlyCat requested changes

2023-02-20 07:33 UTC, GodlyCat approved these changes

2023-02-20 08:16 UTC, stas1408123 approved these changes

2023-02-20 08:16 UTC, stas1408123 commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +            var categories = _mapper.Map<List<CategoryViewModel>>(_categoryRepository.GetCategories()); //without automapper - var categories = _categoryRepository.GetCategory()
var categories = _categoryRepository.GetCategories()
return _mapper.Map<List<CategoryViewModel>>(categories)

2023-02-20 08:16 UTC, stas1408123 commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +
remove empty string

2023-02-20 08:16 UTC, merged