Services (moved Upd, Create & Del into Services)
GodlyCat/Pokemons pull request #6
Opened 2023-02-20 13:08 UTC by SasukeVapes

Created Services, minor changes in controllers (almost all return's have mappings now )

2023-02-21 07:00 UTC, Genresal commented on PokemonReviewApi/PokemonReviewApi/Controllers/CountryController.cs
>          }
The same point about null and a blank line below the comment.)

2023-02-21 09:30 UTC, SasukeVapes commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
>          }
At some point in the future I might need to return deletedCategory or even deleted categoryId for informational purposes or debugging. Therefore I'd like to keep "return null" for now.

2023-02-21 11:18 UTC, Genresal approved these changes

2023-02-22 02:11 UTC, GodlyCat requested changes
Why not for all controllers was created services. 
Why you keep use repositories in controllers
Why not all methods implemented inside services

2023-03-01 08:14 UTC, GodlyCat requested changes
We shouldn't return short vm's from controller 

Same for services, u should return response from repositories on create and update

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +            _categoryService.CreateCategory(categoryMap);
Return response from service on create (map model to full vm and return this)

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CountryController.cs
> +            _countryService.CreateCountry(countryMap);
same

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
> +            _categoryService.UpdateCategory(categoryId, categoryMap);
same

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CountryController.cs
> +            _countryService.UpdateCountry(countryId, countryMap);
same

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/OwnerController.cs
> +            _ownerService.CreateOwner(countryId, ownerMap);
same

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/OwnerController.cs
> +            _ownerService.UpdateOwner(countryId, ownerId, ownerMap);
same

2023-03-01 08:14 UTC, GodlyCat commented on PokemonReviewApi/PokemonReviewApi/Controllers/CategoryController.cs
>          public CategoryShortViewModel GetCategory(int categoryId)
why you return short vm ?

2023-03-03 07:49 UTC, Glipchik commented on PokemonReviewApi/PokemonReviewApi/Services/IServices/IPokemonService.cs
> +        List<Pokemon> GetPokemons();
You probably could add blank lines between these methods to improve the visual perception

2023-03-03 07:50 UTC, Glipchik commented on PokemonReviewApi/PokemonReviewApi/Helper/MappingProfiles.cs
> +            CreateMap<Category, CategoryViewModel>().ReverseMap();
And some blank lines between mappings of different entities might be useful here too

2023-03-03 07:53 UTC, Glipchik commented on PokemonReviewApi/PokemonReviewApi/Services/IServices/IPokemonService.cs
> +        List<Pokemon> GetPokemons();
Also it is not the best idea to put the folder with interfaces inside the folder with services. You may create the separate folder in the project called 'Interfaces' or 'Abstractions' and put these interfaces there

2023-03-03 07:53 UTC, Glipchik approved these changes

2023-03-03 08:21 UTC, GodlyCat approved these changes

2023-03-03 08:34 UTC, merged